[workspace]
members = [
    "common",
    "entity",
    "engine",
    "history",
    "rest",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
strip = "symbols"
codegen-units = 1

[profile.perf]
inherits = "release"
debug = 2
strip = "none"
